// Generates src/data/gameFeed.ts from data/game_2_weighted_score.csv.
// The feed is the ENTIRE game timeline (every play-by-play row), in order, so
// the simulated broadcast streams the whole game rather than a curated reel.
//
// Run: node scripts/genGameFeed.mjs
//
// Per row we carry: period, clock (MM:SS), forward-filled score (so the
// scoreboard stays correct through rebounds/misses/subs that have no score),
// tone (good/bad/neutral from the `bucket` column), a short emphasis `tag`,
// and the signed, time-weighted `impact` (drives the MSG shockwave size).

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const CSV = resolve(ROOT, "data/game_2_weighted_score.csv");
const OUT = resolve(ROOT, "src/data/gameFeed.ts");

const raw = readFileSync(CSV, "utf8").trim().split(/\r?\n/);
raw.shift(); // header: period,clock,abs_seconds_elapsed,score,event_text,bucket,impact_score,reason_code

/** Split a row, tolerating commas inside event_text (4 leading + 3 trailing fields). */
function parseRow(line) {
  const p = line.split(",");
  return {
    period: parseInt(p[0], 10),
    clock: p[1],
    score: p[3],
    text: p.slice(4, p.length - 3).join(","),
    bucket: p[p.length - 3],
    impact: parseFloat(p[p.length - 2]),
    reason: p[p.length - 1],
  };
}

/** "11:36.0" -> "11:36", "0:07.5" -> "0:07" */
const cleanClock = (c) => c.replace(/\.\d+$/, "");

/** Drop running point totals; keep assist context. */
const cleanText = (t) => t.replace(/\s*\(\d+\s+PTS\)/g, "").trim();

function team(reason) {
  if (reason.startsWith("NYK")) return "NYK";
  if (reason.startsWith("SAS")) return "SAS";
  return null;
}

function deriveTag(r) {
  const t = team(r.reason);
  const txt = r.text;
  const tp = (label) => (t ? `${t} ${label}` : label);
  if (/Alley Oop/i.test(txt)) return tp("ALLEY-OOP");
  if (/Dunk/i.test(txt)) return tp("DUNK");
  if (r.reason.includes("MADE_3") || (/3PT/.test(txt) && r.reason.includes("MADE"))) return tp("3");
  if (r.reason.includes("MADE_2")) return tp("2");
  if (r.reason.includes("MADE_FT") || /Free Throw/i.test(txt)) return tp("FT");
  if (r.reason.includes("STEAL")) return tp("STEAL");
  if (r.reason.includes("BLOCK")) return tp("BLOCK");
  if (r.reason.includes("TOV") || /Turnover/i.test(txt)) return tp("TOV");
  if (/Timeout/i.test(txt)) return "TIMEOUT";
  return undefined;
}

const moments = [];
let lastScore = "0-0";
for (let i = 0; i < raw.length; i++) {
  const r = parseRow(raw[i]);
  if (r.score && r.score !== "-") lastScore = r.score;

  const isLast = i === raw.length - 1;
  const isPeriodEnd = /^End of .*Period/i.test(r.text);

  let tag = deriveTag(r);
  let text = cleanText(r.text);
  let tone = r.bucket;

  if (isLast && isPeriodEnd) {
    // Final buzzer — drives "Knicks win it!" headline + "Final" status.
    tag = "FINAL";
    text = "Final buzzer — Knicks win it!";
    tone = "good";
  } else if (r.reason.includes("CLUTCH") && Math.abs(r.impact) >= 12) {
    tag = "CLUTCH";
  }

  moments.push({
    period: r.period,
    clock: cleanClock(r.clock),
    score: lastScore,
    text,
    tone,
    tag,
    impact: r.impact,
  });
}

const lit = (m) => {
  const parts = [
    `period: ${m.period}`,
    `clock: ${JSON.stringify(m.clock)}`,
    `score: ${JSON.stringify(m.score)}`,
    `text: ${JSON.stringify(m.text)}`,
    `tone: ${JSON.stringify(m.tone)}`,
  ];
  if (m.tag) parts.push(`tag: ${JSON.stringify(m.tag)}`);
  parts.push(`impact: ${m.impact}`);
  return `  { ${parts.join(", ")} },`;
};

const header = `// AUTO-GENERATED by scripts/genGameFeed.mjs from data/game_2_weighted_score.csv.
// Do not edit by hand — re-run the script to regenerate. This is the FULL Game 2
// (Knicks vs. Spurs, MSG) play-by-play, streamed in order by the live-feed
// ticker. Each moment is tagged good/bad/neutral from a Knicks-fan POV.

export type FeedTone = "good" | "bad" | "neutral";

export interface FeedMoment {
  /** Game period (1-4). */
  period: number;
  /** Game clock at the moment, e.g. "8:41". */
  clock: string;
  /** Score as NYK-SAS at the moment (forward-filled through non-scoring plays). */
  score: string;
  /** Short, fan-facing description. */
  text: string;
  tone: FeedTone;
  /** Optional emphasis label, e.g. "DUNK", "AND-1", "DAGGER". */
  tag?: string;
  /**
   * Swing-aware, time-weighted impact of the moment, signed from a Knicks-fan
   * POV (+ good, − bad). Sourced from data/game_2_weighted_score.csv; |impact|
   * ranges ~0–16 (clutch late-game plays spike highest). Drives how big/crazy
   * the MSG shockwave animation goes.
   */
  impact: number;
}

export const FINAL_SCORE = { nyk: 105, sas: 104 } as const;

export const HOME = { name: "Knicks", fullName: "New York Knicks", tricode: "NYK" } as const;
export const AWAY = { name: "Spurs", fullName: "San Antonio Spurs", tricode: "SAS" } as const;

// Ordered chronologically. The ticker plays through these to simulate the feed.
export const GAME_FEED: FeedMoment[] = [
`;

writeFileSync(OUT, header + moments.map(lit).join("\n") + "\n];\n");
mkdirSync(dirname(OUT), { recursive: true });
console.log(`Wrote ${moments.length} moments to ${OUT}`);
